import type { SourceType } from './types';

export const DEFAULT_PHONE_COUNTRY = 'IN';

export const SOURCE_WEIGHTS: Record<SourceType, number> = {
  ats_json: 0.95,
  csv: 0.85,
  linkedin: 0.8,
  github: 0.7,
  resume: 0.75,
  notes: 0.6
};

export const SKILL_ALIAS_MAP: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  ml: 'Machine Learning',
  machinelearning: 'Machine Learning',
  'machine learning': 'Machine Learning',
  'react.js': 'React',
  reactjs: 'React',
  react: 'React',
  nodejs: 'Node.js',
  node: 'Node.js',
  'node.js': 'Node.js',
  k8s: 'Kubernetes',
  kubernetes: 'Kubernetes',
  'spring boot': 'Spring Boot',
  springboot: 'Spring Boot',
  aws: 'AWS',
  gcp: 'Google Cloud',
  'google cloud': 'Google Cloud',
  postgres: 'PostgreSQL',
  postgresql: 'PostgreSQL',
  kafka: 'Kafka',
  redis: 'Redis',
  python: 'Python',
  java: 'Java',
  docker: 'Docker',
  terraform: 'Terraform',
  sql: 'SQL'
};

export const COUNTRY_ALIAS_MAP: Record<string, string> = {
  india: 'IN',
  in: 'IN',
  bharat: 'IN',
  'united states': 'US',
  usa: 'US',
  us: 'US',
  america: 'US',
  'united kingdom': 'GB',
  uk: 'GB',
  greatbritain: 'GB',
  britain: 'GB',
  canada: 'CA',
  ca: 'CA',
  australia: 'AU',
  au: 'AU',
  germany: 'DE',
  de: 'DE',
  france: 'FR',
  fr: 'FR',
  italy: 'IT',
  it: 'IT',
  spain: 'ES',
  es: 'ES',
  netherlands: 'NL',
  nl: 'NL',
  singapore: 'SG',
  sg: 'SG',
  japan: 'JP',
  jp: 'JP',
  china: 'CN',
  cn: 'CN',
  brazil: 'BR',
  br: 'BR',
  mexico: 'MX',
  mx: 'MX',
  southafrica: 'ZA',
  'south africa': 'ZA',
  za: 'ZA',
  uae: 'AE',
  'united arab emirates': 'AE',
  ae: 'AE',
  ireland: 'IE',
  ie: 'IE',
  sweden: 'SE',
  se: 'SE',
  norway: 'NO',
  no: 'NO',
  finland: 'FI',
  fi: 'FI',
  denmark: 'DK',
  dk: 'DK',
  switzerland: 'CH',
  ch: 'CH',
  austria: 'AT',
  at: 'AT',
  belgium: 'BE',
  be: 'BE',
  portugal: 'PT',
  pt: 'PT',
  poland: 'PL',
  pl: 'PL',
  'new zealand': 'NZ',
  nz: 'NZ'
};

export const DATE_MONTHS: Record<string, number> = {
  january: 1,
  february: 2,
  march: 3,
  april: 4,
  may: 5,
  june: 6,
  july: 7,
  august: 8,
  september: 9,
  october: 10,
  november: 11,
  december: 12
};